name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set Swift version
      run: |
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        swiftenv install 5.1 --set-global
    - name: Swift test
      run: swift test
