name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup linux toolchain
      run: |
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      swiftenv global 4.2
      if: matrix.os == 'ubuntu-latest'
    - name: Swift test
      run: swift test
